# Configuration file for .github/workflows/ci.yml

DirectoryPath: "_site"
# Jekyll's directory structure triggers this:
IgnoreDirectoryMissingTrailingSlash: true

# This does not "ignore" the broken links, but it does not fail the action
# From the htmltest README:
# When true produces a warning, rather than an error, for broken external links.
IgnoreExternalBrokenLinks: true
